export default [
{
    id: 1,
    user: {
        verified: false,
        name: 'I Am Devloper',
        screen_name: 'iamdeveloper',
        picture: {thumbnail: 'https://pbs.twimg.com/profile_images/477397164453527552/uh2w1u1o.jpeg'},
    },
    is_retweet: false,
    retweet_user: {},
    retweeted: false,
    liked: true,
    text: '',
    media_src: 'https://pbs.twimg.com/media/C-_VHfeXsAAe45K.jpg:large',
    media_expanded: false,
    time: '2017-04-05 16:50',
    reply_count: 322,
    retweet_count: 2842,
    like_count: 2842
},
{
    id: 2,
    user: {
        verified: true,
        name: 'Carter Wilkerson‏',
        screen_name: 'carterjwm',
        picture: {thumbnail: 'https://pbs.twimg.com/profile_images/812351185994719232/MwMySyMz_400x400.jpg'},
    },
    is_retweet: false,
    retweet_user: {},
    retweeted: true,
    liked: true,
    text: 'HELP ME PLEASE. A MAN NEEDS HIS NUGGS',
    media_src: 'https://pbs.twimg.com/media/C8sk8QlUwAAR3qI.jpg:large',
    media_expanded: false,
    time: '2017-04-05 16:50',
    reply_count: 1120200,
    retweet_count: 3400200,
    like_count: 893230
},
{
    id: 3,
    user: {
        verified: false,
        name: 'Eric Elliot',
        screen_name: '_ericelliot',
        picture: {thumbnail: 'https://pbs.twimg.com/profile_images/464310668984725504/ym-M-SNv.jpeg'},
    },
    is_retweet: true,
    retweet_user: {
        verified: false,
        name: 'Daniel Blomdahl',
        screen_name: 'blomdahldaniel',
        picture: {thumbnail: 'https://pbs.twimg.com/profile_images/823597626457210881/pPNqyM1k.jpg'}
    },
    retweeted: false,
    liked: false,
    text: 'Java is to JavaScript as pain is to painting.',
    media_src: '',
    media_expanded: false,
    time: '2017-03-08 13:37',
    reply_count: 12,
    retweet_count: 302,
    like_count: 212
},
{
    id: 4,
    user: {
        verified: false,
        name: 'Donald J. Trump',
        screen_name: 'notRealDonaldTrump',
        picture: {thumbnail: 'https://pbs.twimg.com/profile_images/773623721802207237/vxMHCDtc_400x400.jpg'},
    },
    is_retweet: false,
    retweet_user: {},
    retweeted: true,
    liked: true,
    text: 'China built a wall, and they have almost no Mexicans',
    media_src: 'http://i1.kym-cdn.com/photos/images/original/001/092/938/d98.gif',
    media_expanded: false,
    time: '2017-02-01 16:50',
    reply_count: 1342000,
    retweet_count: 3420000,
    like_count: 893000
},
{
    id: 5,
    user: {
        verified: true,
        name: 'Renzo Soprano‏',
        screen_name: 'Renzo_Soprano',
        picture: {thumbnail: 'https://pbs.twimg.com/profile_images/608406499879219202/FUjv4eLg_400x400.jpg'},
    },
    is_retweet: false,
    retweet_user: {},
    retweeted: false,
    liked: true,
    text: 'Evolution continues as pregnant women are now able to provide free Wi-Fi',
    media_src: 'https://pbs.twimg.com/media/CLZT1YjWwAA8m_p.jpg:large',
    media_expanded: false,
    time: '2015-08-02 16:50',
    retweet_count: 1312,
    retweet_count: 5512,
    like_count: 5032
},
{
    id: 6,
    user: {
        verified: false,
        name: 'Elle Oh Hell',
        screen_name: 'ElleOhHell',
        picture: {thumbnail: 'https://pbs.twimg.com/profile_images/833104828385619977/HdV_Ik9h_400x400.jpg'},
    },
    is_retweet: false,
    retweet_user: {},
    retweeted: false,
    liked: false,
    text: 'I started carrying a knife after an attempted mugging a few years ago. Since then, my mugging attempts have been a lot more successful.',
    media_src: '',
    media_expanded: false,
    time: '2015-02-15 18:50',
    reply_count: 3264,
    retweet_count: 8564,
    like_count: 13611
},
{
    id: 7,
    user: {
        verified: false,
        name: 'Chelsea Lockwood',
        screen_name: 'Chelsea_Elle',
        picture: {thumbnail: 'https://pbs.twimg.com/profile_images/845444041680416768/8wtFdiNa.jpg'},
    },
    is_retweet: false,
    retweet_user: {},
    retweeted: false,
    liked: true,
    text: 'Leaving my browser history open in case anyone in this coffee shop tries to steal my laptop when I\'m in the bathroom.',
    media_src: 'https://pbs.twimg.com/media/Bi4AL8MCAAAZ0Mo.jpg',
    media_expanded: false,
    time: '2014-03-16 21:20',
    reply_count: 12407,
    retweet_count: 20832,
    like_count: 33920
},
];
